sudo: false
dist: trusty
language: python
env:
  global:
  - TPQ_URL=postgresql://postgres@localhost/tpq
  matrix:
  - DJANGO=1.10
services:
- postgresql
addons:
  postgresql: '9.5'
python:
- '3.5'
install:
- make dependencies
before_script:
- psql -c 'create database tpq' -U postgres
script:
- make travis
after_success:
- make coveralls
deploy:
  provider: pypi
  user: "Ben.Timby"
  password:
    secure: "JnrnEkb838olUSM10vodjGgNhkdbIORxMbMWRGbRPBVMg9ZaoLMLrIeIJ5Zy3IE8aib17RQzAisrpF0e8ZEzqb0ACXyxZhWR/Y6R0UR/E8we0bZYZOaCEv0tb42s+X/TtyIOl/eYgULyODyb7w3Tnw98Ip4LvscswLcfHvoLjnW6fN5RJ8zCyzoqoyY76lUGWm3HzSwZXSx11H4qoKKVH+MsWuYXgie06/e2HkIn+gtRycfj0q3GxEe1aGk1c6tWdRtI89OjIl5Vt0lstqGidXzGheN4JwIetRmlqnrAHUbUBrIpQ3+Aa6dmYDeqmVTcBb28f3AWoDtMG0Bcu1eu37hA7OBhQIq2J/uS4hxhEBfjnbl+oEAgCtZNoNhKxzSqnxcB6KLXYBysJr6alUC99PifYgIVGBwd+sHp/Ivo+lWpLY6AojJtVZvXsCJq9c021tF0EkphQ7UtTaOfJ6PqQqr3oBuxelPKqKAkqCAeblz5zCbD2LyOIH+OfbIGRQUdL3LSduSQzMsjuVPU1wZ3U6xIAvm8pPHg6dh21vYd3HW1DnHm36YZroffjTR5jwDFVvxJTOcP9mHg++2eqc+LXzJ+B+MVKAH38t79V3pqKY7IpsjoQIAIM1AFTv0/LHbLe4MLGZlAQ2YRd/SoOaju2VVyk5e9eLgjd19DEWdSew8="
  on:
    tags: true
